In [151]:
%matplotlib inline

In [152]:
from __future__ import print_function
import torch

# Tensor
`torch.Tensor`是类似于`ndarray`的一种类型

### 1 创建 Tensor 的方法

In [153]:
x = torch.empty(5,3)    #空矩阵
print(x)

tensor([[1.9015e-09, 4.5902e-41, 2.3304e-14],
        [3.0787e-41, 4.4842e-44, 0.0000e+00],
        [1.5695e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 5.9503e-01, 1.9318e-01],
        [8.9442e-01, 4.3411e-01, 2.8936e-01]])


In [154]:
x = torch.rand(5,3)    #随机矩阵
print(x)

tensor([[0.9184, 0.0375, 0.4793],
        [0.7603, 0.7391, 0.3048],
        [0.6797, 0.9656, 0.3686],
        [0.1945, 0.3354, 0.9363],
        [0.2437, 0.7085, 0.0621]])


可以定义数据类型`dtype` = `torch.long` `torch.double` `torch.float`等等

In [155]:
x = torch.zeros(5,3, dtype=torch.double)   #零矩阵  
print(x)      

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [156]:
x = torch.tensor(
    [[5.5, 3],
    [2, 5]])   #直接写出完整的矩阵
print(x)

tensor([[5.5000, 3.0000],
        [2.0000, 5.0000]])


**从已有的 tensor 建立新的 tensor：**  

1) 使用`.new_ones` `.new_zeros`系列的函数。需要给出`size`,其他属性默认继承，可以修改。

In [157]:
x = x.new_ones(5, 4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


2) 使用`torch.zeros_like()`系列的函数。原 tensor 的`size`将作为参数决定新数组的大小，其他属性默认继承，可以修改。

In [158]:
x = torch.zeros_like(x)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [159]:
print(x.size())

torch.Size([5, 4])


### 2 Tensor 的操作

**加法：**  

1) 两 tensor 相加，使用 `+` 或 `torch.add()`

In [160]:
x = torch.rand(5,3)
y = torch.zeros(5,3)

In [161]:
x+y

tensor([[0.3446, 0.5674, 0.0146],
        [0.0776, 0.7300, 0.2629],
        [0.3711, 0.5864, 0.9410],
        [0.7334, 0.4571, 0.9023],
        [0.7648, 0.2262, 0.6958]])

In [162]:
torch.add(x,y)

tensor([[0.3446, 0.5674, 0.0146],
        [0.0776, 0.7300, 0.2629],
        [0.3711, 0.5864, 0.9410],
        [0.7334, 0.4571, 0.9023],
        [0.7648, 0.2262, 0.6958]])

2) 一个 tensor 加到另一个上面，使用`.add_()`,如果使用`.add()`则不会修改原数组。

In [163]:
y.add_(x)
print(y)

tensor([[0.3446, 0.5674, 0.0146],
        [0.0776, 0.7300, 0.2629],
        [0.3711, 0.5864, 0.9410],
        [0.7334, 0.4571, 0.9023],
        [0.7648, 0.2262, 0.6958]])


**slice**

In [93]:
print(x[0:-2, 1:3]) #先切出几行，再切出几列

tensor([[0.8483, 0.5721],
        [0.6466, 0.0706],
        [0.5130, 0.3021]])


**reshape**  
使用`.view()`

In [103]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)     #-1表示系统自动计算数值
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**others**

使用`.item()`从只有一个元素的 tensor 中提取数值

In [105]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1638])
-1.1638457775115967


### 3 Tensor 和 ndarray 的转换

In [164]:
import numpy as np

**Tensor -> ndarray**

In [165]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [166]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


注意，在使用了`b = a.numpy()`后，不是简单地赋值给 b, 而是将 a 和 b 联系起来了，修改 a 的时候 b 也会被修改。

In [169]:
print(a.add_(1))
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


**ndarray -> Tensor**

In [170]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [171]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### 4 CUDA Tensors

使用`device`类以及使用`.to()`命令转移 Tensor 到不同设备。

In [178]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[1.3446, 1.5674, 1.0146],
        [1.0776, 1.7300, 1.2629],
        [1.3711, 1.5864, 1.9410],
        [1.7334, 1.4571, 1.9023],
        [1.7648, 1.2262, 1.6958]], device='cuda:0')
tensor([[1.3446, 1.5674, 1.0146],
        [1.0776, 1.7300, 1.2629],
        [1.3711, 1.5864, 1.9410],
        [1.7334, 1.4571, 1.9023],
        [1.7648, 1.2262, 1.6958]], dtype=torch.float64)


从代码里面看起来，即使我们的环境是pytorch(gpu)，我们也需要把 Tensor 移动到 CUDA 中才能使用 GPU 计算。